### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by mnce92** [kakorcal/bubble-shooter#1]
Hi, the demo link isnt working, and it isnt working as well in my local environment. Only pale green background came out but not the game itself. 

p.s. : I'm a beginner in phaser and learning.

**Comment by kakorcal** [comment]
Hey there,
Sorry for getting to this late. I updated the link to http://html5bubbleshooter.surge.sh/ if you want to check it out. As far as running it locally, doing a `npm start` on your terminal from the root of the directory and going to `http://localhost:3000` is all you have to do. Make sure you run `npm install` to get the dependencies before you run the dev server.

Let me know if you need further help.
Best,
Kenneth
