### ISSUE TITLE
html5bubbleshooter.co offline

### ISSUE THREAD

**Issue by bitelchux** [kakorcal/bubble-shooter#2]
Hi, the website of the sample project is offline (html5bubbleshooter.co)
I would like to take a look to the game, but I am not able of building the project, could you provide the bundle javascript file (compiled and built) or a sample url where I could get the "raw" javascript file/s (without building anything, only static phaser javascript file/s)?
Best regards
  Julio

**Comment by kakorcal** [comment]
Hi Julio.
Thanks for checking out this project. This was a small project I made for friends so I'm currently not actively working on this atm. I updated the link to point to http://html5bubbleshooter.surge.sh/ . Let me know if you have any issues accessing it. 
Best,
Kenneth
